name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Okbuck CI Checks
    env:
      SKIP_OKBUCK: true
      EXTRA_OKBUCK_ARGS: "--quiet --stacktrace"
      EXTRA_BUCK_ARGS: "-v 0"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_cmd: [build, lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run ${{ matrix.build_cmd }}
        run: ./tooling/ci/build_cmd.sh ${{ matrix.build_cmd }}
      - name: Upload snapshot
        run: ./gradlew publish --no-daemon --no-parallel -PSONATYPE_NEXUS_USERNAME="$SONATYPE_NEXUS_USERNAME" -PSONATYPE_NEXUS_PASSWORD="$SONATYPE_NEXUS_PASSWORD" && ./gradlew closeAndReleaseRepository
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SonatypeUsername }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SonatypePassword }}
        if: success() && github.ref == 'refs/heads/master' && github.event_name != 'pull_request' && matrix.java_version == '8'
